### ISSUE TITLE
if twitter version change your code become useless :/

### ISSUE THREAD

**Issue by d0m00re** [dilaouid/hardcore-twitter#5]
The twitter class names are probably generated automatically by a bundler.

I advise you to use an xPath to find the elements to hide or to use the api data to locate your element.

For exemple 👍 :
solution 1 :
/html/body/div[1]/div/div/div[2]/main/div/div/div/div[2]/div/div[2]/div/div/div/div[3]/div/section/div/div
(inpect / get xpath)

**Comment by dilaouid** [comment]
yo bro
sadly xpath changes depending on the screensize ;_;
we talked about this but i keep this issue open gigachad

**Comment by dilaouid** [comment]
5 months later and still working fine (dab)
